### ISSUE TITLE
Add Support for Dear ImGui extensions

### ISSUE THREAD

**Issue by bennett-harvey** [mosra/magnum-integration#101]
I've set up a Magnum project with ImGui integration enabled, and I want to try out some [ImGui extensions](https://github.com/ocornut/imgui/wiki/Useful-Extensions). A lot of them (such as [ImGuizmo](https://github.com/CedricGuillemet/ImGuizmo)) are laid out as just a set of cpp/h files to be added directly to a project in the same way Dear ImGui itself is added. 

I'm pretty new to CMake, so I'm not sure how to set this up myself with Magnum's CMake structure. It would be nice if I could specify CMake variables to provide any number of arbitrary cpp/h files to be added alongside the base Dear ImGui files. And to make things easier with git subdirectories, it would be best if these files didn't have to actually be in the same directory (IMGUI_DIR).

**Comment by Squareys** [comment]
Hey @bennett-harvey !

You should be able to just use the files with your project. We're using ImGuizmo, implot in a project and it works fine :)
