### ISSUE TITLE
i get an error when i am trying running a robotic simulation with robot_dart and magnum

### ISSUE THREAD

**Issue by pngsyr** [mosra/magnum-integration#103]
DartIntegration::convertShapeNode(): AssimpImporter is not available and you are trying to load a dart::dynamics::MeshShape this is the error.

**Comment by mosra** [comment]
Hi, you need to have Magnum Plugins available with the [AssimpImporter plugin](https://doc.magnum.graphics/magnum/classMagnum_1_1Trade_1_1AssimpImporter.html) enabled for this library to work.

Assuming this is related to `robot_dart`, the project probably has some existing setup script to make the plugin available and found by the library :)
