### ISSUE TITLE
Cannot find ImGuiIntegration methods

### ISSUE THREAD

**Issue by Fattorino** [mosra/magnum-integration#107]
Hello, me again.
This is actually the first time I work with rendering so I'm mainly messing around to understand how the pieces fit together.
I know possibli the best way to render a 3D scene inside an ImGui window is to use ImGui::Image(), so doing a bit of reading I saw [this](https://doc.magnum.graphics/magnum/namespaceMagnum_1_1ImGuiIntegration.html#func-members). When I went to try it I couldn't find those methods anywhere.
Are those outdated? Is there a better way to render a GL::Framebuffer to an ImGui window I'm not aware of maybe?
Thanks in advance

**Comment by mosra** [comment]
[`#include <Magnum/ImGuiIntegration/Widgets.h>`](https://github.com/mosra/magnum-integration/blob/master/src/Magnum/ImGuiIntegration/Widgets.h), the appropriate include is listed if you click on details of those functions.

Just FYI, feel free to join the Gitter chat at https://gitter.im/mosra/magnum (you can log in with your GitHub account), you'll get a quicker response there without the whole ceremony of having to open a GitHub issue first :)
