### ISSUE TITLE
BulletIntegration: btlDebugDraw implementation for Magnum.

### ISSUE THREAD

**Issue by Squareys** [mosra/magnum-integration#11]
Hello everybody!

While working with Bullet for a bit, I found this [btlDebugDraw](http://bulletphysics.org/Bullet/BulletFull/classbtIDebugDraw.html) class/interface which is supposed to be dervied with implementations for simple primitive drawing methods. It can then be attached to a `btCollisionWorld` or `btDynamicsWorld` for example, to provide fast and simple means of debug rendering.

I suggest this could be a great thing to have in the BulletIntegration library, since its code would most likely be common for all Magnum apps which use bullet.

(This is in no way urgent and if I have time, I might event implement this myself later next year. Just wanted to put that out there for discussion.)

Greetings, Squareys

**Comment by mosra** [comment]
Hah, sorry, this somehow completely slipped through my attention...

Now I think this would be a much better approach than having those "shape converters", considering I'm about to deprecate/remove the half-~~assed~~implemented shapes library (https://github.com/mosra/magnum/issues/148).

**Comment by Squareys** [comment]
We need to implement these methods of that interface:
 * virtual void setDebugMode (int debugMode)=0
 * virtual int getDebugMode () const =0
 * virtual void drawLine (const btVector3 &from, const btVector3 &to, const btVector3 &color)=0
 * virtual void reportErrorWarning (const char *warningString)=0
 * virtual void draw3dText (const btVector3 &location, const char *textString)=0
 * virtual void flushLines()

Everything else is already implemented using the `drawLine()` method. I suggest building a buffer with all the lines and then drawing that on `flushLines()`. That buffer needs to be updated every frame, so that's not optimal, but it's only for debug rendering anyway.

**Comment by mosra** [comment]
Implemented via #21.
