### ISSUE TITLE
BulletIntegration broken on Ubuntu 16.06 with GCC 5.4

### ISSUE THREAD

**Issue by Alicemargatroid** [mosra/magnum-integration#23]
The annotation:

    CORRADE_UNUSED

Is used on member functions:

    drawContactPoint
    draw3dText

in file:

    BulletIntegration/DebugDraw.h

This does not appear to be recognized as a valid annotation in GCC 5.4 on Ubuntu 16.06, possibly due to a lacking include? This is precluding me from compiling, but removing the annotation is a quick and easy fix.

**Comment by mosra** [comment]
Argh, it seems that this (and other things) slipped through my review.

Fixed in 92227c20104fe8623b070449185c1d5f0e3bf49f.
