### ISSUE TITLE
Minor typo in DartIntegration

### ISSUE THREAD

**Issue by costashatz** [mosra/magnum-integration#30]
ocurrs --> occurs

https://github.com/mosra/magnum-integration/blob/1348abd067824649cd0f4557da5c0e4b0a8d663e/src/Magnum/DartIntegration/World.h#L68

**Comment by mosra** [comment]
Dang, missed this in all the notifications. Fixed in 0f9ab78dfd9f043c3ae2a171fae4a05d8e6166e6. Thanks!
