### ISSUE TITLE
Minor LibOvrIntegration API changes

### ISSUE THREAD

**Issue by mosra** [mosra/magnum-integration#4]
- rename all `getSomething()` methods to `something()` for consistency (`Hmd` and `SwapTextureSet` classes)
- return `std::array<DualQuaternion, 2>` from `Hmd::getEyePoses()`/`Hmd::eyePoses()` instead of `std::unique_ptr`, no need to do heap allocation in this case
- rename `LibOvrIntegration::LibOvrContext` to just `LibOvrIntegration::Context` (also consistency, the header is already named like that)

cc @Squareys

**Comment by Squareys** [comment]
@mosra Do you want the first change only for those two classes? I know at least two more classes off the top of my head which would require some renaming aswell.

**Comment by mosra** [comment]
right... all of them, of course (I thought it were only these two)

**Comment by mosra** [comment]
Oh, this should have been closed for quite some time :)

**Comment by Squareys** [comment]
@mosra Yes, indeed, thank you! And thank you for cleaning up after once again (in 3cd924ec51ea0580ea7fdbc3dbc4b5869c4f8da8 and following).

**Comment by mosra** [comment]
I needed to create `compatibility` branch for AppVeyor CI, the cleanup was just a byproduct :)
