### ISSUE TITLE
CMake error when generating the imgui example

### ISSUE THREAD

**Issue by Melix19** [mosra/magnum-integration#49]
I tried to generate the [imgui example](https://github.com/mosra/magnum-examples/tree/master/src/imgui) and I read that I need to set the IMGUI_DIR to the location of imgui to work. But when generating the project this error shows up:

<img width="877" alt="image" src="https://user-images.githubusercontent.com/23530586/61550397-a1329e00-aa52-11e9-8f8c-3d1200808ac4.png">

Doing some research I found [this](https://gitter.im/mosra/magnum/archives/2019/05/03?at=5ccc3cbca4ef097471413069) and the solution of commenting [this](https://github.com/mosra/magnum-examples/blob/221050342f99b525149d127fa05eeb57a304c4a3/modules/FindMagnumIntegration.cmake#L285-L288) lines has worked for me too (but won't compile). IDK if this is a CMake problem or not.

Magnum version: 2019.01
OS: macOS 10.14.5
CMake version: 3.15.0

**Comment by mosra** [comment]
Hi!

Commenting the lines out will only postpone the problem further to the build time, yes. Silly question -- did you build integration with `WITH_IMGUI` enabled? It's not enabled by default. If you did, there should be a file named `/usr/local/lib/libMagnumImGuiIntegration.dylib` or something like that and CMake should find it correctly. The `IMGUI_DIR` needs to be set both when the integration is built and when the example is built.

> Magnum version: 2019.01

Unless the above solved that for you, this might be *also* the problem. Can you try with current master? You'll need also master of corrade and all other deps.

**Comment by Melix19** [comment]
I used homebrew to install magnum-integration, so maybe in the formula the imgui integration is not present? (I have not found /usr/local/lib/libMagnumImGuiIntegration.dylib so I guess the answer is yes)

**Comment by mosra** [comment]
Oh, no, it's not, as there's no ImGui package in Homebrew to depend on. You need to build the integration lib yourself from source -- but since you have all other deps installed via homebrew, it shouldn't be too hard.

**Comment by Melix19** [comment]
Ok, I managed to fix it. I just downloaded the homebrew-formulas and I modified the cmake flags to make the imgui integration build. Thank you.

**Comment by mosra** [comment]
To make it easier for whoever runs into this problem next I mentioned this limitation in the building docs (65dd13d074293b733bb42dd3ffca931a9720fbae).
