### ISSUE TITLE
Redefinition errors including ImGuiIntegration/Context.hpp multiple times

### ISSUE THREAD

**Issue by Melix19** [mosra/magnum-integration#50]
When including the ImGuiIntegration/Context.hpp multiple times (when for example there are two files that include ImGuiIntegration/Context.hpp and these files are included in another file) the compiler gives several redefinition errors.
This is due to missing `#pragma once` or `#ifndef/#define` in the ImGuiIntegration/Context.hpp file.

**Comment by mosra** [comment]
Ugh. Sorry about that. All the headers guards were messed up for some reason, fixed in a3609bcf5fd32665db3b16b5c67cbfed6a5a7f8a.
