### ISSUE TITLE
error: no member named 'RGBA8' in 'Magnum::GL::TextureFormat'(Cross-compiling for Emscripten)

### ISSUE THREAD

**Issue by linuxaged** [mosra/magnum-integration#54]
when build target wasm:

	C:\workspace\magnum-integration\build-emscripten>cmake .. -G Ninja -DCMAKE_TOOLCHAIN_FILE="../toolchains/generic/Emscripten-wasm.cmake"  -DCMAKE_BUILD_TYPE=Release  -DEMSCRIPTEN_PREFIX="C:/workspace/emsdk/fastcomp/emscripten" -DCMAKE_PREFIX_PATH="C:/lib/emscripten/system" -DWITH_IMGUI=ON -DIMGUI_DIR="C:/workspace/imgui" -DCMAKE_INSTALL_PREFIX="C:/lib/emscripten/system" -DMAGNUM_DEPLOY_PREFIX="C:/http/magnum" -DCMAKE_FIND_ROOT_PATH="C:/lib/emscripten/system" -DCMAKE_MAKE_PROGRAM="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe"
	-- Found Magnum: C:/lib/emscripten/system/include
	-- Found Magnum: C:/lib/emscripten/system/include  found components:  GL
	-- Configuring done
	-- Generating done
	CMake Warning:
	  Manually-specified variables were not used by the project:

	    CMAKE_TOOLCHAIN_FILE

	-- Build files have been written to: C:/workspace/magnum-integration/build-emscripten

Got the error:

	C:\workspace\magnum-integration\build-emscripten>cmake --build . --target install
	[2/8] Building CXX object src/Magnum/ImGuiIntegration/CMakeFiles/MagnumImGuiIntegration.dir/Context.cpp.o
	FAILED: src/Magnum/ImGuiIntegration/CMakeFiles/MagnumImGuiIntegration.dir/Context.cpp.o
	C:\workspace\emsdk\fastcomp\emscripten\em++.bat  -DIMGUI_USER_CONFIG=\"Magnum/ImGuiIntegration/visibility.h\" -I../src -Isrc -isystem C:/lib/emscripten/system/include/MagnumExternal/OpenGL -isystem C:/lib/emscripten/system/include -isystem C:/workspace/imgui -s WASM=1 -Wno-warn-absolute-paths -DNDEBUG -O3 -O3 -DNDEBUG   -std=c++11 -Wall -Wextra -Wold-style-cast -Winit-self -Werror=return-type -Wmissing-declarations -pedantic -fvisibility=hidden -fvisibility-inlines-hidden -Wmissing-prototypes -Wno-shorten-64-to-32 -MD -MT src/Magnum/ImGuiIntegration/CMakeFiles/MagnumImGuiIntegration.dir/Context.cpp.o -MF src\Magnum\ImGuiIntegration\CMakeFiles\MagnumImGuiIntegration.dir\Context.cpp.o.d -o src/Magnum/ImGuiIntegration/CMakeFiles/MagnumImGuiIntegration.dir/Context.cpp.o -c ../src/Magnum/ImGuiIntegration/Context.cpp
	../src/Magnum/ImGuiIntegration/Context.cpp:226:47: error: no member named 'RGBA8' in 'Magnum::GL::TextureFormat'
	            .setStorage(1, GL::TextureFormat::RGBA8, image.size())
	                           ~~~~~~~~~~~~~~~~~~~^
	1 error generated.
	shared:ERROR: 'C:/workspace/emsdk/fastcomp/fastcomp/bin\clang++.exe -target asmjs-unknown-emscripten -D__EMSCRIPTEN_major__=1 -D__EMSCRIPTEN_minor__=38 -D__EMSCRIPTEN_tiny__=46 -D_LIBCPP_ABI_VERSION=2 -Werror=implicit-function-declaration -Xclang -nostdsysteminc -Xclang -isystemC:\workspace\emsdk\fastcomp\emscripten\system\include\libcxx -Xclang -isystemC:\workspace\emsdk\fastcomp\emscripten\system\lib\libcxxabi\include -Xclang -isystemC:\workspace\emsdk\fastcomp\emscripten\system\include\compat -Xclang -isystemC:\workspace\emsdk\fastcomp\emscripten\system\include -Xclang -isystemC:\workspace\emsdk\fastcomp\emscripten\system\include\libc -Xclang -isystemC:\workspace\emsdk\fastcomp\emscripten\system\lib\libc\musl\arch\emscripten -Xclang -isystemC:\workspace\emsdk\fastcomp\emscripten\system\local\include -DIMGUI_USER_CONFIG="Magnum/ImGuiIntegration/visibility.h" -I../src -Isrc -isystem C:/lib/emscripten/system/include/MagnumExternal/OpenGL -isystem C:/lib/emscripten/system/include -isystem C:/workspace/imgui -DNDEBUG -O3 -O3 -DNDEBUG -std=c++11 -Wall -Wextra -Wold-style-cast -Winit-self -Werror=return-type -Wmissing-declarations -pedantic -fvisibility=hidden -fvisibility-inlines-hidden -Wmissing-prototypes -Wno-shorten-64-to-32 -MD -MT src/Magnum/ImGuiIntegration/CMakeFiles/MagnumImGuiIntegration.dir/Context.cpp.o -MF src\Magnum\ImGuiIntegration\CMakeFiles\MagnumImGuiIntegration.dir\Context.cpp.o.d -c -DEMSCRIPTEN -mllvm -disable-llvm-optzns ../src/Magnum/ImGuiIntegration/Context.cpp -Xclang -disable-O0-optnone -Xclang -isystemC:\workspace\emsdk\fastcomp\emscripten\system\include\SDL -c -o src/Magnum/ImGuiIntegration/CMakeFiles/MagnumImGuiIntegration.dir/Context.cpp.o -emit-llvm' failed (1)
	[6/8] Building CXX object src/Magnum/ImGuiIntegration/CMakeF...es/MagnumImGuiIntegration.dir/C_/workspace/imgui/imgui.cpp.o
	C:/workspace/imgui/imgui.cpp:13998:27: warning: unused variable 'backup_dock_id' [-Wunused-variable]
	            const ImGuiID backup_dock_id = window->DockId;
	                          ^
	1 warning generated.
	ninja: build stopped: subcommand failed.

**Comment by Squareys** [comment]
Hey @linuxaged !

This is intended behaviour, please use `RGBA` on WebGL 1.0 (see [the documentation](https://doc.magnum.graphics/magnum/namespaceMagnum_1_1GL.html#a97b777c3a35e1efd11bbbe565982926cab4b279046a02077466fa26cabb00c642))

Best,
Jonathan

**Comment by mosra** [comment]
The `ImGuiIntegration` currently works only on WebGL 2.0, sorry. If you build magnum with `TARGET_GLES2` set to `OFF`, you'll get a WebGL 2 build and then the above error will go away.

A WebGL 1 port is planned at some point in the future, but no clear date or milestone for that right now.
