### ISSUE TITLE
OvrIntegration does not compile with OVR SDK 0.6.0.1

### ISSUE THREAD

**Issue by mosra** [mosra/magnum-integration#6]
Details: https://ci.appveyor.com/project/mosra/magnum-integration/build/compatibility-6 (apparently just some enum value mismatches).

0.6.0.0 works w/o problem.

**Comment by Squareys** [comment]
Alright, I'll be on this as of the 1st of August.

**Comment by mosra** [comment]
Thank you!

**Comment by mosra** [comment]
Done with #7
