### ISSUE TITLE
[arch] build fails - lwop_ivec3 not defined

### ISSUE THREAD

**Issue by marinjurjevic** [mosra/magnum-integration#70]
I have glm-0.9.9.8-1 installed. Build fails on following file/line:
<details>
   <summary> error log </summary>

```make
 Build files have been written to: /home/marin/magnum-root/magnum-integration/build
[3/4] Building CXX object src/Magnum/GlmIntegration...eFiles/GlmIntegrationTest.dir/IntegrationTest.cpp.o
FAILED: src/Magnum/GlmIntegration/Test/CMakeFiles/GlmIntegrationTest.dir/IntegrationTest.cpp.o 
/usr/bin/c++  -DCORRADE_IS_DEBUG_BUILD -I../src -Isrc -isystem /usr/include/MagnumExternal/OpenGL -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -g   -std=c++11 -Wall -Wextra -Wold-style-cast -Winit-self -Werror=return-type -Wmissing-declarations -Wpedantic -fvisibility=hidden -fvisibility-inlines-hidden -Wzero-as-null-pointer-constant -Wdouble-promotion -MD -MT src/Magnum/GlmIntegration/Test/CMakeFiles/GlmIntegrationTest.dir/IntegrationTest.cpp.o -MF src/Magnum/GlmIntegration/Test/CMakeFiles/GlmIntegrationTest.dir/IntegrationTest.cpp.o.d -o src/Magnum/GlmIntegration/Test/CMakeFiles/GlmIntegrationTest.dir/IntegrationTest.cpp.o -c ../src/Magnum/GlmIntegration/Test/IntegrationTest.cpp
../src/Magnum/GlmIntegration/Test/IntegrationTest.cpp: In member function ‘void Magnum::GlmIntegration::Test::{anonymous}::IntegrationTest::debugVec()’:
../src/Magnum/GlmIntegration/Test/IntegrationTest.cpp:470:25: error: ‘lowp_ivec3’ is not a member of ‘glm’; did you mean ‘lowp_dvec3’?
  470 |     Debug{&out} << glm::lowp_ivec3{1, 42, -3};
      |                         ^~~~~~~~~~
      |                         lowp_dvec3
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
    Aborting...
```
</details>

I have searched for this lowp_ivec3 and on my machine it is defined in `/usr/include/glm/gtc/type_precision.hpp:1295`

On the official API doc of [type_precision.hpp](https://glm.g-truc.net/0.9.9/api/a00174_source.html), in that same file type is not defined nor mentioned. 
After some digging, I found in API docs that `lwop_ivec3` is defined in [glm/ext/vector_int3_precision.hpp](https://glm.g-truc.net/0.9.9/api/a00219.html). 

I am totally confused now, I honestly just want build to pass at this point.

**Comment by marinjurjevic** [comment]
Well, it seems API docs are relative to 0.9.9.7 version which is the one available to download from official website...
Is there anywhere info on which library versions are specific repos depending on?

**Comment by mosra** [comment]
I have no idea either, these types just disappeared in the latest release and nothing in the changelog mentioned them (as usual).

I had fixed this locally for quite some while, but forgot to push it -- sorry about that. Should be working with 63084d67781e4dd3a8fbc6da48c9af1bac628d79 again.
