### ISSUE TITLE
Update to Oculus SDK 0.7.0.0 (as of 27th of August)

### ISSUE THREAD

**Issue by Squareys** [mosra/magnum-integration#8]
Hi everybody, 

[Oculus SDK 0.7 will be coming soon](https://developer.oculus.com/blog/upcoming-oculus-pc-sdk-0-7-compatibility-changes/) (20th of August), and LibOvrIntegration will be updated accordingly once it is released. This may require some changes to the API of LibOvrIntegration, so keep that in mind :)

Greetings, Squareys.

**Comment by Squareys** [comment]
Oculus delayed the release of Oculus SDK 0.7 by a week, in case you are wondering why this is so silent.

Greetings, Squareys.

**Comment by Squareys** [comment]
https://developer.oculus.com/downloads/pc/0.7.0.0-beta/Oculus_SDK_for_Windows/ *phew*, this is going to be something.

**Comment by mosra** [comment]
Huh, that's a lot API changes there :)

Because the API is being changed anyway, what do you say about shortening the namespace a bit and naming it just `OvrIntegration`?

**Comment by Squareys** [comment]
> what do you say about shortening the namespace a bit and naming it just OvrIntegration?

Sure, why not. This only regards the namespaces, though, right? The project will still be called "LibOvrIntegration"?

**Comment by mosra** [comment]
I'd like to have everything consistent -- `WITH_OVR` CMake option, `<Magnum/OvrIntegration/OvrIntegration.h>` include, `OvrIntegration` namespace and `MagnumOvrIntegration` library.

**Comment by Squareys** [comment]
Okay, will do, if the prject would have been named different than the namespace, that would have led to confusion.

**Comment by mosra** [comment]
Wanted to do the rename before the code makes it into a tagged release, because then we would need to maintain backward compatibility (which would be rather painful in this case).

**Comment by mosra** [comment]
Done with #9.
