### ISSUE TITLE
Linking failure with ImGui HEAD

### ISSUE THREAD

**Issue by Gollum999** [mosra/magnum-integration#81]
Looks like ImGui added a new source file in a recent commit: [imgui_tables.cpp](https://github.com/ocornut/imgui/blob/master/imgui_tables.cpp).  This causes linking errors like the following:

```
imgui.obj : error LNK2019: unresolved external symbol "void __cdecl ImGui::EndTable(void)" (?EndTable@ImGui@@YAXXZ) referenced in function "void __cdecl Im
Gui::ErrorCheckEndFrameRecover(void (__cdecl*)(void *,char const *,...),void *)" (?ErrorCheckEndFrameRecover@ImGui@@YAXP6AXPEAXPEBDZZ0@Z) [C:\code\SaikoEng
ine\bld\vs\external\magnum-integration\src\Magnum\ImGuiIntegration\MagnumImGuiIntegration.vcxproj]
imgui_demo.obj : error LNK2001: unresolved external symbol "void __cdecl ImGui::EndTable(void)" (?EndTable@ImGui@@YAXXZ) [C:\code\SaikoEngine\bld\vs\extern 
al\magnum-integration\src\Magnum\ImGuiIntegration\MagnumImGuiIntegration.vcxproj]
```

I see the list of expected source file is hard-coded [here](https://github.com/mosra/magnum-integration/blob/11ed4febe2e10d9ddc06b8cdce64311e04195982/modules/FindImGui.cmake#L151).  Presumably that will need to change, and change in such a way that it supports both old and new versions of ImGui.

**Comment by pezcode** [comment]
If you pull master again, that should be fixed with https://github.com/mosra/magnum-integration/commit/1f79ba71b9f0ece204dd9ba31b06871653c0d546 :eyes:

**Comment by Gollum999** [comment]
Seems to work.  Thanks for the quick fix!
