### ISSUE TITLE
MSYS .gitattributes typo: Wrong line ending normalization under Windows

### ISSUE THREAD

**Issue by lacyyy** [mosra/magnum-integration#97]
Typo in https://github.com/mosra/magnum-integration/blob/master/package/msys/.gitattributes
```
magnum/PKGBUILD text eof=lf
PKGBUILD text eof=lf
```
There is no attribute named eof, they're supposed to be eol attributes.
Because of this typo, Git on Windows wrongly normalizes the PKGBUILD files to CRLF line endings.
Last time I reported this typo in the other magnum repos I didn't know this repo existed 😄

**Comment by mosra** [comment]
Pushed (with you as an author) as 49f345923539eb56240c3179e14a552e31e058c3. Sorry again for the mess! :D
